config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "flights#index"
  get '/flights', to: 'flights#index'
  get '/bookings/new', to: 'bookings#new'
  get '/bookings/:id', to: 'bookings#show', as: :booking
  post '/bookings', to: 'bookings#create'
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :arriving_flights, foreign_key: :arrival_id, class_name: 'Flight'
  has_many :departing_flights, foreign_key: :departure_id, class_name: 'Flight'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers, dependent: :destroy
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :arrival_airport, foreign_key: :arrival_id, class_name: 'Airport'
  belongs_to :departure_airport, foreign_key: :departure_id, class_name: 'Airport'
  has_many :bookings
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @flight = Flight.find(params[:flight])
    @booking = @flight.bookings.build
    params[:passengers].to_i.times { @booking.passengers.build }
  end

  def create
    @flight = Flight.find(booking_params[:flight_id])
    @booking = @flight.bookings.build(booking_params)

    if @booking.save
      redirect_to @booking
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id, passengers_attributes: %i[name email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @airports = Airport.all.map { |a| [a.code, a.id] }
    if params[:date]
      @date = hash_to_date(params[:date])
      @flights = Flight.where(departure_id: params[:departure_id], arrival_id: params[:arrival_id], start: (@date..@date+1.month))
    end
  end

  private

  def hash_to_date(hash)
    arr = %w[month year].map { |d| hash["#{d}"].to_i }
    Date.new(arr[1], arr[0], 1)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/_passenger_form.html.erb
<%= form_with model: @booking do |f| %>
  <%= f.label :departure_id, 'Departing from:' %>
  <%= f.text_field :departure_id, value: @flight.departure_airport.name,  disabled: true %>
  <%= f.label :arrival_id, 'To:' %>
  <%= f.text_field :arrival_id, value: @flight.arrival_airport.name,  disabled: true %>
  <%= f.label :passengers, 'Passengers:' %>
  <%= f.text_field :passengers, value: params[:passengers], disabled: true %>
  <%= f.label :date, 'Date' %>
  <%= f.text_field :date, value: @flight.start, disabled: true %>
  <%= f.label :flight_id, 'Flight ID' %>
  <%= f.text_field :flight_id, readonly: true %>
  <% count = 1 %>
  <%= f.fields_for :passengers do |sub_f| %>
    <h3>Passenger #<%= count %></h3>
    <div>
      <%= sub_f.label :name, 'Name' %>
      <%= sub_f.text_field :name %>
    </div>
    <div>
      <%= sub_f.label :email, 'Email' %>
      <%= sub_f.text_field :email %>
    </div>
    <% count += 1 %>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/bookings/new.html.erb
<h1>Booking form</h1>
<h2>Departing from: <%= @flight.departure_airport.name %>(<%= @flight.departure_airport.code %>)</h2>
<h2>To: <%= @flight.arrival_airport.name %>(<%= @flight.arrival_airport.code %>)</h2>
<h2>Date: <%= @flight.start %></h2>
<h2>Number of passengers: <%= params[:passengers] %></h2>

<%= render 'passenger_form' %>

app/views/bookings/show.html.erb
<h1>Booking #<%= @booking.id %></h1>
<ul>
  <p>Passengers:</p>
  <% @booking.passengers.each do |p| %>
    <li><%= p.name %> (<%= p.email %>)</li>
  <% end %>
</ul>
<p>Departing from: <%= @booking.flight.departure_airport.name %> (<%= @booking.flight.departure_airport.id %>)</p>
<p>To: <%= @booking.flight.arrival_airport.name %> (<%= @booking.flight.arrival_airport.id %>)</p>
<p>Date: <%= @booking.flight.start %></p>

app/views/flights/_flights_form.html.erb
<% if @flights && @flights.any? %>
  <%= form_with url: 'bookings/new', method: :get do |f| %>
    <ul class='list-group flight-list'>
      <% @flights.each do |flight| %>
        <li class='list-group-item'>
          <%= f.radio_button :flight, flight.id, class: 'form-check-input' %>
          <%= f.label "flight_#{flight.id}", class: 'form-check-label stretched-link' do %>
            <p>Departing from the <%= flight.departure_airport.name %> (<%= flight.departure_airport.code %>) to
            <%= flight.arrival_airport.name %> (<%= flight.arrival_airport.code %>) at <%= flight.start %></p>
          <% end %>
        </li>
      <% end %>
    </ul>
    <%= f.hidden_field :passengers, value: params[:passengers] %>
    <%= f.submit 'Book', class: 'btn btn-primary submit-button' %>
  <% end %>
<% else %>
  <p>No flights available</p>
<% end %>

app/views/flights/_search_form.html.erb
<%= form_with url: flights_path, method: :get, class: 'flight-form' do |form| %>
  <div class='f-dropdown form-floating'>
    <%= form.select :departure_id, options_for_select(@airports, selected: params[:departure_id]), {}, {class: 'form-select'} %>
    <%= form.label :departure_id, 'Departing from:', class: 'form-label' %>
  </div>
  <div class='f-dropdown form-floating'>
    <%= form.select :arrival_id, options_for_select(@airports, selected: params[:arrival_id]), {}, {class: 'form-select'} %>
    <%= form.label :arrival_id, 'To:', class: 'form-label' %>
  </div>
  <div class='f-dropdown form-floating'>
    <%= form.select :passengers, options_for_select([1, 2, 3, 4], selected: params[:passengers]), {}, {class: 'form-select'} %>
    <%= form.label :passengers, 'Number of passengers:', class: 'form-label' %>
  </div>
  <div class='f-dropdown form-floating'>
    <%= select_month Date.new(2022,8,10), {}, class: 'form-select' %>
    <%= form.label :date, 'Month', class: 'form-label' %>
  </div>
  <div class='f-dropdown form-floating'>
    <%= select_year Date.new(2022,8,10), {start_year: 2022, end_year: 2022}, class: 'form-select' %>
    <%= form.label :date, 'Year', class: 'form-label' %>
  </div>
  <%= form.submit 'Search', class: 'btn btn-primary submit-button' %>
<% end %>

app/views/flights/index.html.erb
<%= render 'search_form' %>

<%= render 'flights_form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>